
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_store
    username: postgres
    password: sudo

  jpa:
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        temp:
          # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
          use_jdbc_metadata_defaults: false
