
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_store
    username: postgres
    password: sudo

  jpa:
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        type: trace
        temp:
          # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
          use_jdbc_metadata_defaults: false
        format-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    ## MULTIPART (MultipartProperties)
    # Enable multipart uploads
    multipart:
      enabled: true
      # Max file size.
      max-file-size: 200MB
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max Request Size
      max-request-size: 215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: E://uploads